server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    home-page-url: http://localhost:8761
    hostname: localhost
    non-secure-port: 8761
    metadata-map:
      allowedAuthorities: ROLE_COFFEENET-ADMIN

spring:
  application:
    name: CoffeeNet Discovery